
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Header from "./Header";
import Footer from "./Footer";


const HomePage = () => {
  const navigate = useNavigate();
    const checkUser=()=>{
      if(localStorage.getItem('token')){
        const role = localStorage.getItem('role');
        if (role === 'student') {
          navigate('/dashboard');
        }
      }
    }
  
    useEffect(() => {
      checkUser();
    }, []);

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-gradient-to-b from-blue-50 to-white">
        <Header />
      <div className="container mx-auto px-4 py-16 flex flex-col items-center text-center">
        <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-800 mb-6">
          Hostel Attendance System
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mb-8">
          A modern solution for tracking and managing student attendance in hostels.
          Simple, secure, and reliable.
        </p>

        {/* {currentUser ? (
          <div className="space-y-4">
            <p className="text-lg text-hostel-primary font-medium">
              Welcome back, {currentUser.name}!
            </p>
            <button
              size="lg"
              onClick={() => 
                navigate(currentUser.role === "admin" ? "/admin/dashboard" : "/dashboard")
              }
            >
              Go to Dashboard
            </button>
          </div>
        ) : ( */}
          <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
            <button
            onClick={() => navigate("/login")}
            className="px-6 py-3 text-white bg-blue-600 hover:bg-blue-700 transition-colors duration-200 rounded-lg shadow-md text-base font-semibold"
            >
            Login
            </button>

            <button
                className="px-6 py-3 text-black bg-white border border-gray-300 hover:border-none hover:bg-green-600 hover:text-white transition-colors duration-200 rounded-lg text-sm font-semibold"
                onClick={() => navigate("/register")}
                >
                Register
                </button>
          </div>
        {/* )} */}
      </div>

      <div className="container mx-auto px-4 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-white p-6 rounded-lg shadow-md hover-scale card-shadow">
            <div className="text-blue-600 font-bold text-xl mb-2">Easy Attendance Marking</div>
            <p className="text-gray-600">
              Students seamlessly mark their daily attendance by scanning a dynamic QR code generated by the system each day.
            </p>
          </div>
          
          <div className="bg-white p-6 rounded-lg shadow-md hover-scale card-shadow">
            <div className="text-blue-600 font-bold text-xl mb-2">Real-time Monitoring</div>
            <p className="text-gray-600">
              Hostel administrators can track attendance in real-time and get insights through detailed reports and visualizations.
            </p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow-md hover-scale card-shadow">
            <div className="text-blue-600 font-bold text-xl mb-2">Export Attendance Data as CSV</div>
            <p className="text-gray-600">
                Easily export attendance records in CSV format for offline analysis and reporting purposes.
            </p>
          </div>
          
          {/* <div className="bg-white p-6 rounded-lg shadow-md hover-scale card-shadow">
            <div className="text-blue-600  font-bold text-xl mb-2">Automated Alerts</div>
            <p className="text-gray-600">
              Automatic notifications to administrators when students are missing or have irregular attendance patterns.
            </p>
          </div> */}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default HomePage;